prefix grasp: <http://groundedannotationframework.org/grasp#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select ?ent (COUNT(DISTINCT ?l) as ?num_mentions) where{
    ?ent rdfs:label %s
    ?l grasp:denotedBy ?e


}